
workload:
	tanzu apps workload apply --file config/workload.yaml --namespace dev-tap --source-image akseutap4registry.azurecr.io/library/vs-extension-sources --debug --yes --local-path . --live-update

status:
	tanzu apps workload get hello-app