apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-app
  labels:
    apps.tanzu.vmware.com/workload-type: app-workload    
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:  
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
